<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2c1f6a4e-7b1d-4f0a-9b53-6c0a3e9d5f21</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreBancario.Application\CoreBancario.Application.csproj" />
    <ProjectReference Include="..\CoreBancario.Infrastructure\CoreBancario.Infrastructure.csproj" />
  </ItemGroup>

</Project>
