// <auto-generated />
using System;
using System.Collections.Generic;
using CoreBancario.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreBancario.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(CoreBancarioDbContext))]
    [Migration("20261006185225_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreBancario.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("CoreBancario.Domain.Cuentas.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaApertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("moneda");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Saldo", "CoreBancario.Domain.Cuentas.Cuenta.Saldo#Dinero", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("saldo_moneda");

                            b1.Property<decimal>("Monto")
                                .HasPrecision(19, 2)
                                .HasColumnType("numeric(19,2)")
                                .HasColumnName("saldo");
                        });

                    b.HasKey("Id")
                        .HasName("pk_cuentas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cuentas_cliente_id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_cuentas_numero");

                    b.ToTable("cuentas", null, t =>
                        {
                            t.HasCheckConstraint("ck_cuentas_fecha_cierre_solo_si_cerrada", "(estado = 'Cerrada') = (fecha_cierre IS NOT NULL)");

                            t.HasCheckConstraint("ck_cuentas_saldo_en_moneda_de_la_cuenta", "saldo_moneda = moneda");

                            t.HasCheckConstraint("ck_cuentas_saldo_no_negativo", "saldo >= 0");
                        });
                });

            modelBuilder.Entity("CoreBancario.Domain.Clientes.Cliente", b =>
                {
                    b.OwnsOne("CoreBancario.Domain.Clientes.Documento", "Documento", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("numero_documento");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("tipo_documento");

                            b1.HasKey("ClienteId");

                            b1.HasIndex("Tipo", "Numero")
                                .IsUnique()
                                .HasDatabaseName("ux_clientes_documento");

                            b1.ToTable("clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId")
                                .HasConstraintName("fk_clientes_clientes_id");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });

            modelBuilder.Entity("CoreBancario.Domain.Cuentas.Cuenta", b =>
                {
                    b.HasOne("CoreBancario.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cuentas_clientes_cliente_id");
                });
#pragma warning restore 612, 618
        }
    }
}
